import 'styles/globals.css';
import { PocketBaseProvider } from 'libs/pocketbase/client';
import type { PropsWithChildren } from 'react';
import { css } from 'styled-system/css';
import { inter } from 'styles/fonts';

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

type RootLayoutProps = PropsWithChildren;

const RootLayout = ({ children }: RootLayoutProps): JSX.Element => {
  return (
    <html lang="en" className={inter.variable}>
      <body className={css({ fontFamily: 'body' })}>
        <PocketBaseProvider>{children}</PocketBaseProvider>
      </body>
    </html>
  );
};

export default RootLayout;
