import 'styles/globals.css';
import { Inter } from 'next/font/google';
import { PocketBaseProvider } from 'libs/pocketbase/client';
import type { PropsWithChildren } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

type RootLayoutProps = PropsWithChildren;

const RootLayout = ({ children }: RootLayoutProps): JSX.Element => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PocketBaseProvider>{children}</PocketBaseProvider>
      </body>
    </html>
  );
};

export default RootLayout;
