import 'styles/globals.css';
import { PocketBaseProvider } from 'lib/pocketbase/client';
import type { PropsWithChildren } from 'react';
import { center } from 'styled-system/patterns';
import { inter } from 'styles/fonts';
import { styled } from 'styled-system/jsx';

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

type RootLayoutProps = PropsWithChildren;

const RootLayout = ({ children }: RootLayoutProps): JSX.Element => {
  return (
    <html lang="en" className={inter.variable}>
      <styled.body h="screen" bg="zinc.900" fontFamily="body" className={center()}>
        <PocketBaseProvider>{children}</PocketBaseProvider>
      </styled.body>
    </html>
  );
};

export default RootLayout;
